### ISSUE TITLE
samples/nodejs-javascript-solutiongallery createConnection failed

### ISSUE THREAD

**Issue by SchneidAIRGoogle** [pnp/graph-connectors-samples#22] opened 2023-11-01 13:46 UTC
npm run createConnection failed

> sample-solution-gallery-connector-node@1.0.0 createConnection
> node createConnection.js

Creating connection...
TypeError: Cannot destructure property 'id' of 'config.connector' as it is undefined.
    at createConnection (file:///C:/Users/ksc.IPIWE/Downloads/pnp%20graph-connectors-samples%20main%20samples-nodejs-javascript-solutiongallery/createConnection.js:7:11)
    at main (file:///C:/Users/ksc.IPIWE/Downloads/pnp%20graph-connectors-samples%20main%20samples-nodejs-javascript-solutiongallery/createConnection.js:52:11)
    at file:///C:/Users/ksc.IPIWE/Downloads/pnp%20graph-connectors-samples%20main%20samples-nodejs-javascript-solutiongallery/createConnection.js:60:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

**Comment by SchneidAIRGoogle** [comment] 2023-11-01 16:55
I am on Node.js v18.18.2.
Should i try another verison?

**Comment by waldekmastykarz** [comment] 2023-11-01 18:24
Let me try to see if I can repro it

**Comment by waldekmastykarz** [comment] 2023-11-01 18:27
I can repro the issue. Sorry for that. I'll get it fixed right away and let you know when it's. So sorry for the trouble

**Comment by waldekmastykarz** [comment] 2023-11-01 18:39
OK, the sample is fixed now. Once again, sorry for the trouble. Please, give it another shot and let us know if everything is working as intended

**Closed** 2023-11-01 18:38 UTC
Labels: bug

**Comment by SchneidAIRGoogle** [comment] 2023-11-01 19:30
Wonderful, dear @waldekmastykarz. It is working now. i had to set the Adaptive Card in Result Type and configured a vertical with this new external Connecrion
![PnPCreateResultType](https://github.com/pnp/graph-connectors-samples/assets/149595386/b1c1017a-5302-426d-a734-7be3bb74525f)
![PnPCreateVertical](https://github.com/pnp/graph-connectors-samples/assets/149595386/1e54a508-d86d-40ef-9971-7797acc8f81d)
![PnPIncludeConnectorResults](https://github.com/pnp/graph-connectors-samples/assets/149595386/1808fd8a-11b3-4eff-8513-926bc7fb8cea)
![PnPNewResultType](https://github.com/pnp/graph-connectors-samples/assets/149595386/856257f1-a486-4c36-a5f4-f151e787eb3e)
![PnPPowershell](https://github.com/pnp/graph-connectors-samples/assets/149595386/07067979-1250-4023-858e-01d1889eab38)
![PnPSemplesMicrosoftSearch](https://github.com/pnp/graph-connectors-samples/assets/149595386/acc0c402-4fb5-47f1-9fd9-1cc2dcf5c375)

**Comment by waldekmastykarz** [comment] 2023-11-02 07:25
Brilliant! While the sample creates a result layout, it doesn't create a vertical because there are no APIs for it as far as I know. Awesome to see it working! How do you like it? Any other samples that you'd like to see?
